namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_REWARD_DISTRIBUTOR_ADDRESS: string;
    NEXT_PUBLIC_REWARD_TOKEN_ADDRESS: string;
    NEXT_PUBLIC_REWARD_SOURCE_NFT_ADDRESS: string;
    NEXT_PUBLIC_IPFS_GATEWAY_URL: string;
    NEXT_PUBLIC_RPC_URL: string;
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: string;
    NEXT_PUBLIC_NETWORK_NAME: string;
  }
}